name: Test
on:
  push:
    tags:
      - v*
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.go-version || 'minimum' }}
    strategy:
      matrix:
        go-version:
          - "" # leave empty to use go-version-file (use go.mod); see https://github.com/actions/setup-go/issues/450#issuecomment-3620402646
          - oldstable
          - stable
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: go.mod # used when go-version is empty.

      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
      - name: Ensure IPVS module
        run: |
          sudo modprobe ip_vs
      - name: Test
        run: |
          go test -exec "sudo -n" -v ./...
  lint:
    permissions:
      contents: read      # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # We only run on the latest version of go, as some linters may be
          # version-dependent (for example gofmt can change between releases).
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.14
          args: --timeout=10m --verbose
          skip-cache: true
